name: Health check

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v2
        with:
          url: https://ancient-fortress-86203.herokuapp.com/health
